apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: aap-job-template-runner
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: CLI
    tekton.dev/tags: ansible, cli
    tekton.dev/displayName: "Ansible Controller cli"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    aap-job-template-runner task simplifies starting jobs

    Ansible Controller (*AWX* is upstream to Controller) is a web-based solution 
    that makes Ansible even more easy to use for IT teams of all kinds, 
    It provides the awx command line tool that simplifies the tasks of starting jobs
  params:
    - name: JOB_TEMPLATE_NAME
      description: The name of job_template to run
      type: string
      default: "--help"
    - name: CONTROLLER_SECRET
      description: The Ansible Controller secret with credentials
      type: string
      default: "controller-credentials"
    - name: APPLICATION_IMAGE
      description: Container image to deploy
      type: string
      default: "registry.access.redhat.com/ubi9/httpd-24"
  steps:
    - name: aap-start-job-template
      image: quay.io/jveverka/awx-cli@sha256:9f0bab98cb81eb149b16a4973129d593a0f0c14e3e98ca11aac5e19e2333bd79
      args:
        - job_templates
        - launch
        - '$(params.JOB_TEMPLATE_NAME)'
        - --extra_vars
        - 'edge_application_image: $(params.APPLICATION_IMAGE)'
        - --monitor
        - -f
        - human
      env:
        - name: CONTROLLER_HOST
          valueFrom:
            secretKeyRef:
              name: $(params.CONTROLLER_SECRET)
              key: CONTROLLER_HOST
        # Either CONTROLLER_USERNAME & CONTROLLER_PASSWORD OR CONTROLLER_OAUTH_TOKEN must be defined!
        - name: CONTROLLER_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.CONTROLLER_SECRET)
              key: CONTROLLER_PASSWORD
              optional: true
        - name: CONTROLLER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.CONTROLLER_SECRET)
              key: CONTROLLER_PASSWORD
              optional: true
        - name: CONTROLLER_OAUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.CONTROLLER_SECRET)
              key: CONTROLLER_OAUTH_TOKEN
              optional: true
